name: flutter_safe_js.dart
description: HTTP RFC1738 / RFC1867 compliant query string encoder and decoder, compatible with the PHP & jQuery traditional syntax for nested array/objects
version: 0.0.1

homepage: https://github.com/evaisse/flutter_safe_js.dart
publish_to: https://pub.dev

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter_safe_js_web: ^0.0.1

flutter:
  plugin:
    platforms:
      android:
      ios:
      macos:
      web:
        default_package: flutter_safe_js_web

dev_dependencies:
  test: ^1.21.1
