name: flutter_safe_js
description: A basic JS bridge to call javascript external context function, seamlessly working on mac/ios/android/...
homepage: https://github.com/evaisse/flutter_safe_js
repository: https://github.com/evaisse/flutter_safe_js/tree/master/packages/flutter_safe_js
issue_tracker: https://github.com/evaisse/flutter_safe_js/issues
version: 0.0.5

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter_safe_js_web: ^0.0.5
  flutter_safe_js_platform_interface: ^0.0.5

dev_dependencies:
  test: ^1.21.1

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_safe_js_platform_interface
      ios:
        default_package: flutter_safe_js_platform_interface
      linux:
        default_package: flutter_safe_js_platform_interface
      macos:
        default_package: flutter_safe_js_platform_interface
      web:
        default_package: flutter_safe_js_web
      windows:
        default_package: flutter_safe_js_platform_interface