name: flutter_safe_js
description: A basic JS bridge to call javascript external context function, seamlessly working on mac/ios/android/...
version: 0.0.1

homepage: https://github.com/evaisse/flutter_safe_js_web.dart
publish_to: https://pub.dev

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter_safe_js_web: ^0.0.1

dev_dependencies:
  test: ^1.21.1

flutter:
  plugin:
    platforms:
      android:
      ios:
      macos:
      web:
        default_package: flutter_safe_js_web
