name: flutter_safe_js_web
description: web interface for flutter_safe_js
homepage: https://github.com/evaisse/flutter_safe_js
repository: https://github.com/evaisse/flutter_safe_js/tree/master/packages/flutter_safe_js_web
issue_tracker: https://github.com/evaisse/flutter_safe_js/issues
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter_safe_js_platform_interface: ^0.0.1

dev_dependencies:
  test: ^1.21.1

flutter:
  plugin:
    implements: flutter_safe_js
    platforms:
      web:
        pluginClass: FlutterSafeJsPlugin
        fileName: flutter_safe_js_web.dart