name: flutter_safe_js_platform_interface
description: Platform interface for flutter_safe_js
homepage: https://github.com/evaisse/flutter_safe_js
repository: https://github.com/evaisse/flutter_safe_js/tree/master/packages/flutter_safe_js_platform_interface
issue_tracker: https://github.com/evaisse/flutter_safe_js/issues
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
